version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/forum
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/forum
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:  
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum 
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./db:/var/lib/mysql